version: "2"
services:
  batch-rekognizer:
    image: turnerlabs/batch-rekognizer:0.1.1
    environment:
      AWS_DEFAULT_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      BUCKET: "${BUCKET}"
      FILE: "${FILE}"
    labels:
      composeToBatch.vcpus: "8"
      composeToBatch.memory: "200000"
